#python
FROM python:3.12-slim

#libki dodatkowe 
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

#zależności Pythona
RUN pip install --no-cache-dir fastapi uvicorn celery opencv-python requests redis python-multipart


COPY . .


EXPOSE 8000